### ISSUE TITLE
Latin transcriptions should not use cyrillic characters

### ISSUE THREAD

**Issue by hwellmann** [Homyakin/iuliia-java#5]
Currently, some schemas map `ё` (U+0451, Cyrillic io) to itself. This mapping should be replaced by `ë` (U+00EB, Latin e with diaeresis).

Use case:
* We use `Translator` to transcribe Russian names, and then further normalize the results by removing diacritics and non-alphabetic characters to store the names in a search index. 
* The search index is expected to contain ASCII characters only, but now contains `е` (U+0435, Cyrillic ie).

**Comment by Homyakin** [comment]
Please, contribute this to https://github.com/nalgeon/iuliia.
